linters:
  enable:
    - containedctx
    - errcheck
    - gosimple
    - govet
    - ineffassign
    - staticcheck
    - unused
    - decorder
    - errname
    - exhaustive
    - exhaustruct
    - forcetypeassert
    - gci
    - gocheckcompilerdirectives
    - gochecknoglobals
    - gochecknoinits
    - goconst
    - godot
    - godox
    - gofmt
    - gofumpt
    - goimports
    - importas
    - misspell
    - musttag
    - nilerr
    - nilnil
    - nlreturn
    - nolintlint
    - paralleltest
    - prealloc
    - predeclared
    - reassign
    - revive
    - sloglint
    - tagalign
    - tagliatelle
    - thelper
    - tparallel
    - unconvert
    - unparam
    - usestdlibvars
    - varnamelen
    - wastedassign
    - whitespace
    - wrapcheck
    - wsl
