version: "0.5"

processes:
  clients:
    command: watchexec -w . -w $$DB_FILE -- go run . clients list
    is_tty: true
  projects:
    command: watchexec -w . -w $$DB_FILE -- go run . projects list
    is_tty: true
  tasks:
    command: watchexec -w . -w $$DB_FILE -- go run . tasks list
    is_tty: true
  sqlc:
    command: watchexec -w queries.sql -- sqlc generate
    is_tty: true
  just:
    command: watchexec -w justfile -w 'just' -- just
    is_tty: true
  test:
    command: watchexec -w . -- go test ./...
    is_tty: true
