version: "0.5"
is_strict: true
processes:
  tidy:
    command: watchexec -- go mod tidy -v
    disabled: false

  generate:
    command: watchexec -- go generate -v ./...
    disabled: false

  test:
    command: gotestsum ./...
    disabled: false
    is_tty: true

  run:
    command: go run . client
    disabled: false
    is_tty: true
