version: "0.5"
is_strict: true
processes:
  tidy:
    command: watchexec -- go mod tidy -v
    disabled: false

  generate:
    command: watchexec -- go generate -v ./...
    disabled: false

  test:
    disabled: true
    command: gotestsum ./... -- -count=1

  run:
    disabled: true
    command: go run .

  test-watch:
    namespace: watch
    disabled: true
    is_tty: true
    command: watchexec -- gotestsum ./...

  run-watch:
    namespace: watch
    disabled: true
    is_tty: true
    command: watchexec -- go run .
