// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0

package queries

type Client struct {
	ID   int64
	Name string
}

type Entry struct {
	ID     int64
	Name   string
	TaskID int64
}

type Project struct {
	ID       int64
	Name     string
	ClientID int64
}

type Task struct {
	ID        int64
	Name      string
	ProjectID int64
}
