// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0

package queries

type Client struct {
	ID   int64
	Name string
}

type Project struct {
	ID       int64
	Name     string
	ClientID int64
}
